### ISSUE TITLE
Improve style of search page

### ISSUE THREAD

**Issue by amzoss** [minicomp/wax-facets#17]
aggressive flashing when typing, generally poor style of results

**Comment by amzoss** [comment]
Flashing should be fixed by sticky footer
to improve style:
- put image on left and details on right like https://minicomp.github.io/wax/search/
- but maybe a squarer box for image
- less metadata on right, cleaner
- https://liturgical.columbia.edu/search/ may be better model

**Comment by amzoss** [comment]
changes up on https://github.com/minicomp/wax-facets/tree/search-page

@elotroalex want to check to see if you like it? feel free to add more changes or we can merge and close this if it looks okay

**Comment by amzoss** [comment]
![Screen Shot 2021-08-06 at 12 10 05 PM (2)](https://user-images.githubusercontent.com/4193810/128540047-3acf5dc6-8fe6-43d5-96ae-fb0f7f7f808f.png)

screenshot of current style (note: not using new sticky footer yet)

**Comment by elotroalex** [comment]
I like this new style! I say merge this one!

**Comment by amzoss** [comment]
Yay! Will do!
