### ISSUE TITLE
Search index generation rake task failing

### ISSUE THREAD

**Issue by quinnanya** [minicomp/wax-facets#22]
Hi! On a new install using just this repo, I tried to run the search index rake task and got this error:

bundle exec rake wax:search qatar --trace
** Invoke wax:search (first_time)
** Execute wax:search
rake aborted!
WaxTasks::Error::InvalidConfig: 
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/wax_tasks-1.1.2/lib/wax_tasks/config.rb:58:in `search'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/wax_tasks-1.1.2/lib/wax_tasks/site.rb:59:in `generate_static_search'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/wax_tasks-1.1.2/lib/tasks/search.rake:13:in `block (3 levels) in <top (required)>'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/wax_tasks-1.1.2/lib/tasks/search.rake:13:in `each'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/wax_tasks-1.1.2/lib/tasks/search.rake:13:in `block (2 levels) in <top (required)>'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/Users/qad/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/Users/qad/.rbenv/versions/2.6.0/bin/rake:23:in `load'
/Users/qad/.rbenv/versions/2.6.0/bin/rake:23:in `<top (required)>'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/lib/bundler/cli/exec.rb:63:in `load'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/lib/bundler/cli/exec.rb:28:in `run'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/lib/bundler/cli.rb:494:in `exec'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/lib/bundler/cli.rb:30:in `dispatch'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/lib/bundler/cli.rb:24:in `start'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/exe/bundle:49:in `block in <top (required)>'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/Users/qad/.gem/ruby/2.6.0/gems/bundler-2.2.4/exe/bundle:37:in `<top (required)>'
/Users/qad/.rbenv/versions/2.6.0/bin/bundle:23:in `load'
/Users/qad/.rbenv/versions/2.6.0/bin/bundle:23:in `<main>'
Tasks: TOP => wax:search

**Comment by elotroalex** [comment]
This is interesting. I can't recreate this on my computer. I'm also using ruby 2.6.0 and the same version of wax as facets does. Hmmmmm. I just regenerated.

**Comment by quinnanya** [comment]
Happy to try things if you've got debugging suggestions! I could also try on another laptop to see if that makes a difference.

**Comment by elotroalex** [comment]
No clue what to try here. Oh, I just noticed what was wrong! You say

`bundle exec rake wax:search qatar` 

but it's actually:

`bundle exec rake wax:search main`

The search task is different like that. The explanation is in [the "search" article on the wiki](https://minicomp.github.io/wiki/wax/running-the-tasks/search/). 

Phew! Ok, closing.
