### ISSUE TITLE
Make facets functionality easy to export to another theme

### ISSUE THREAD

**Issue by elotroalex** [minicomp/wax-facets#24]
- [ ]  Go over the whole site to make sure the facets functions are modular enough
- [ ] Try to move them from Facets to regular Wax Theme
- [ ] Make documentation for how to do it

**Comment by elotroalex** [comment]
Created this one for you @quinnanya :)

**Comment by quinnanya** [comment]
🙏🏻 Grateful!

**Comment by elotroalex** [comment]
couldn't be easier now!
