### ISSUE TITLE
create a new layout for facet gallery

### ISSUE THREAD

**Issue by amzoss** [minicomp/wax-facets#28]
right now loading javascript for facets in default layout and thus adding it to all pages unnecessarily. should create a new layout to load the javascript that is only used for pages with a facet gallery.

**Comment by elotroalex** [comment]
opting for a YAML header value instead. It became clear real quick that a layout wasn't gonna work very well because you want to use these things anywhere. Right now we have them in a layout exhibit and in a page layout. The YAML header is something like:

```
gallery: True
```
