### ISSUE TITLE
Display multi-value facets without separator on item layout page

### ISSUE THREAD

**Issue by jocelynpender** [minicomp/wax-facets#49]
Is it possible to display multi-value data with a prettier separator on item layout pages? For example, my `jurisdiction` facet has multi-values separated by pipes, and displays these pipes on my item layout (example: https://atlantichabitatmodels.github.io/data/inputs/accdc/). It would be nice to print them with a comma instead 😄 
I guess I could use comma as my multi-value separator to solve this issue?

**Comment by amzoss** [comment]
Yes, you could change the separator in the original metadata file, or you could probably also process the data in the [item metadata include](https://github.com/minicomp/wax-facets/blob/main/_includes/item_metadata.html). You could try passing value to a [split](https://shopify.github.io/liquid/filters/split/) on "|", and then [join](https://shopify.github.io/liquid/filters/join/) the array back up with a different separator.

**Comment by jocelynpender** [comment]
Thank you for your help @amzoss! If anyone stumbles upon this issue in the future, they can check out how I resolved this in my repo: https://github.com/atlantichabitatmodels/data/commit/4d4b1c0fad7059a2247923f31264ab5e66f30a2e
